### ISSUE TITLE
v0.4 task list

### ISSUE THREAD

**Issue by asemposki** [asemposki/SAMBA#4]
To-do before the new release of the BAND software suite:
- [x] Finish generating documentation for each Python module
- [x] Write in information about each class at the top of each page in the API
- [x] Fix the doctoring rendering

**Comment by asemposki** [comment]
Only need to flesh out some of the documentation now. Simple paragraphs and such.

**Comment by asemposki** [comment]
Documentation is now complete.
